# Generated by Django 5.1.12 on 2025-09-15 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogindexpage_appear_in_search_results_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="enable_search",
            field=models.BooleanField(
                default=True, help_text="Aktifkan form pencarian di index ini"
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="posts_per_page",
            field=models.PositiveIntegerField(
                default=9,
                help_text="Jumlah posting per halaman",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(60),
                ],
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="show_archives",
            field=models.BooleanField(default=True, help_text="Tampilkan widget Arsip"),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="show_categories",
            field=models.BooleanField(
                default=True,
                help_text="Tampilkan widget Kategori (sibling BlogIndexPage)",
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="show_popular_tags",
            field=models.BooleanField(
                default=True, help_text="Tampilkan widget Tag Populer"
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="show_recent",
            field=models.BooleanField(
                default=True, help_text="Tampilkan widget Terbaru"
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="show_rss",
            field=models.BooleanField(default=True, help_text="Tampilkan widget RSS"),
        ),
    ]
