# Generated by Django 5.1.12 on 2025-09-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blogindexpage_enable_search_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="enable_comments",
            field=models.BooleanField(
                default=True, help_text="Aktifkan komentar pada halaman ini"
            ),
        ),
    ]
